# Generated by Django 5.1.3 on 2024-11-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matrícula')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('n_quadro', models.CharField(max_length=100, verbose_name='Número do Quadro')),
                ('n_motor', models.CharField(max_length=100, verbose_name='Número do Motor')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('km', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('data_criacao_inspecao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação da Inspeção')),
                ('data_proxima_inspecao', models.DateField(verbose_name='Data da Próxima Inspeção')),
                ('deficiencias', models.TextField(blank=True, null=True, verbose_name='Deficiências')),
                ('n_ficha', models.CharField(editable=False, max_length=6, unique=True, verbose_name='Número da Ficha')),
            ],
            options={
                'verbose_name': 'Inspeção Veicular',
                'verbose_name_plural': 'Inspeções Veiculares',
                'ordering': ['matricula'],
            },
        ),
    ]
