# Generated by Django 5.1.3 on 2024-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano_fabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('tipo_veiculo', models.CharField(max_length=50, verbose_name='Tipo de Veículo')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('numero_motor', models.CharField(max_length=50, verbose_name='Número do Motor')),
                ('numero_quadro', models.CharField(max_length=50, verbose_name='Número do Quadro')),
                ('nome_proprietario', models.CharField(max_length=100, verbose_name='Nome Completo do Proprietário')),
                ('endereco_rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('endereco_numero', models.CharField(max_length=10, verbose_name='Número')),
                ('endereco_bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('endereco_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endereco_provincia', models.CharField(max_length=50, verbose_name='Província')),
                ('endereco_codigo_postal', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('numero_registro', models.CharField(max_length=50, unique=True, verbose_name='Número do Registro')),
                ('local_registro', models.CharField(max_length=100, verbose_name='Local de Registro')),
                ('documento_identidade', models.CharField(max_length=50, verbose_name='Documento de Identidade')),
            ],
            options={
                'verbose_name': 'Registro de Matrícula',
                'verbose_name_plural': 'Registros de Matrículas',
            },
        ),
    ]
